name: Manual workflow
on:
  workflow_dispatch: 
env:
  DOCKER_IMAGE_NAME: my-example-app:${{ github.run_number }}
  MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  MEND_URL: ${{ vars.MEND_URL }}
  MEND_EMAIL: ${{ vars.MEND_EMAIL }}
jobs:
  MendPOCpython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MendPOC
        run: |
          python test.py
          - name: Download Mend CLI & Run an image Scan
          run: |
              curl -LO https://downloads.mend.io/production/unified/latest/linux_amd64/mend
              chmod +x mend
              ./mend image $DOCKER_IMAGE_NAME    

