name: Manual workflow
on:
  workflow_dispatch: 
env:
  MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  MEND_URL: ${{ vars.MEND_URL }}
  MEND_EMAIL: ${{ vars.MEND_EMAIL }}
jobs:
  MendPOCpython:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run MendPOC
        run: |
          python test.py
          - name: Download Mend CLI & Run an image Scan
          run: |
            echo Downloading Mend CLI
            curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
            echo run Mend dependencies scan
            mend dep -u
            echo Run Mend code scan
            mend code   

